START_DATE="2015-01-01"
END_DATE=None

RAW_DATA_OUTPUT_PATH="data/raw/stocks.parquet"
RAW_BENCHMARK_OUTPUT_PATH="data/raw/benchmark.parquet"
PROCESSED_BENCHMARK_OUTPUT_PATH="data/processed/benchmark.parquet"
DATASET_OUTPUT_PATH="data/processed/stocks.parquet"

BENCHMARK_TICKER="^GSPC"

NIFTY50_TICKERS = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "ICICIBANK.NS",
    "INFY.NS", "HINDUNILVR.NS", "ITC.NS", "SBIN.NS",
    "BHARTIARTL.NS", "KOTAKBANK.NS", "LT.NS", "AXISBANK.NS",
    "ASIANPAINT.NS", "MARUTI.NS", "SUNPHARMA.NS",
    "TITAN.NS", "ULTRACEMCO.NS", "WIPRO.NS", "NESTLEIND.NS",
    "BAJFINANCE.NS", "BAJAJFINSV.NS", "HCLTECH.NS",
    "POWERGRID.NS", "NTPC.NS", "TATAMOTORS.NS",
    "ONGC.NS", "COALINDIA.NS", "JSWSTEEL.NS", "TATASTEEL.NS",
    "INDUSINDBK.NS", "HDFCLIFE.NS", "SBILIFE.NS",
    "ADANIENT.NS", "ADANIPORTS.NS", "BRITANNIA.NS",
    "CIPLA.NS", "DIVISLAB.NS", "DRREDDY.NS",
    "EICHERMOT.NS", "GRASIM.NS", "HEROMOTOCO.NS",
    "HINDALCO.NS", "IOC.NS", "M&M.NS",
    "SHREECEM.NS", "TECHM.NS", "UPL.NS",
    "APOLLOHOSP.NS", "BAJAJ-AUTO.NS"
]

